"""drop field foreign keys

Revision ID: 253299321431
Revises: 0009_refactor_versioning
Create Date: 2026-07-29 12:26:21.441324
"""

from alembic import op
import sqlalchemy as sa


revision = '253299321431'
down_revision = '0009_refactor_versioning'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admins_email_key', 'admins', type_='unique')
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.drop_constraint('uq_file_storage_file_key', 'file_storage', type_='unique')
    op.drop_index('ix_file_storage_file_key', table_name='file_storage')
    op.create_index(op.f('ix_file_storage_file_key'), 'file_storage', ['file_key'], unique=True)
    op.drop_constraint('file_uploads_field_id_fkey', 'file_uploads', type_='foreignkey')
    op.drop_constraint('form_versions_link_token_key', 'form_versions', type_='unique')
    op.drop_index('ix_form_versions_link_token', table_name='form_versions')
    op.create_index(op.f('ix_form_versions_link_token'), 'form_versions', ['link_token'], unique=True)
    op.drop_index('ix_forms_status', table_name='forms')
    op.drop_constraint('response_answers_field_id_fkey', 'response_answers', type_='foreignkey')
    op.drop_constraint('response_answers_field_option_id_fkey', 'response_answers', type_='foreignkey')
    op.add_column('validation_errors', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('validation_errors_field_id_fkey', 'validation_errors', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('validation_errors_field_id_fkey', 'validation_errors', 'fields', ['field_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('validation_errors', 'updated_at')
    op.create_foreign_key('response_answers_field_option_id_fkey', 'response_answers', 'field_options', ['field_option_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('response_answers_field_id_fkey', 'response_answers', 'fields', ['field_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_forms_status', 'forms', ['status'], unique=False)
    op.drop_index(op.f('ix_form_versions_link_token'), table_name='form_versions')
    op.create_index('ix_form_versions_link_token', 'form_versions', ['link_token'], unique=False)
    op.create_unique_constraint('form_versions_link_token_key', 'form_versions', ['link_token'])
    op.create_foreign_key('file_uploads_field_id_fkey', 'file_uploads', 'fields', ['field_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_file_storage_file_key'), table_name='file_storage')
    op.create_index('ix_file_storage_file_key', 'file_storage', ['file_key'], unique=False)
    op.create_unique_constraint('uq_file_storage_file_key', 'file_storage', ['file_key'])
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.create_unique_constraint('admins_email_key', 'admins', ['email'])
    # ### end Alembic commands ###
